apiVersion: v1
kind: Pod
metadata:
  name: helloworld-box
  namespace: demo-namespace
  annotations:
    city: neuville
  labels:
    app: db
    environment: staging
    tier: backend
spec:
  containers:
  - name: helloworld-test
    image: apache/causeway-app-helloworld
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 80
